languaje: java

addons:
  sonarcloud:
    organization: "azoriussergh4-github"
    token:
      secure: "**************************" # encrypted value of your token 
script:
  - cd Backend
   # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
