version: "3.3"
services:
  app:
    image: azoriussergh/colorconfluence
    ports:
      - "8080:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.58/colorconfluence?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: sergio
      SPRING_DATASOURCE_PASSWORD: ColorConfluence4$$