version: "3.8"
services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: colorconfluence
  app:
    image: azoriussergh/colorconfluence
    depends_on:
      - database
    ports:
      - "8080:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database/colorconfluence?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        SPRING_DATASOURCE_USERNAME: sergio
        SPRING_DATASOURCE_PASSWORD: ColorConfluence4$